micronaut:
  http:
    client:
      default-client:
        default:
          uri: http://localhost:8080 # Configuração padrão do HttpClient
        customized:
          uri: http://localhost:8080 # URL da API externa
          propagation: io.micronaut.tracing.propagation.TracePropagation.ThreadLocal




micronaut:
  http:
    client:
      default-client: customized
